//! Parse and serialize 7 Days to Die's `serverconfig.xml`.
//!
//! The format is essentially:
//! ```xml
//! <?xml version="1.0"?>
//! <ServerSettings>
//!   <!-- a comment about the next group -->
//!   <property name="ServerName" value="My Server"/>
//!   <property name="ServerPort" value="26900"/>
//! </ServerSettings>
//! ```
//!
//! We preserve the order of `<property>` elements and any inter-element
//! comments so the file round-trips cleanly. Unknown elements are dropped
//! (the file format only uses `<property>` and comments in practice).

use std::path::Path;

use anyhow::{anyhow, Context, Result};
use quick_xml::events::{BytesDecl, BytesEnd, BytesStart, BytesText, Event};
use quick_xml::reader::Reader;
use quick_xml::writer::Writer;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum ConfigItem {
    /// `<property name="..." value="..."/>`
    Property { name: String, value: String },
    /// `<!-- ... -->` — preserved so we can round-trip the file.
    Comment { text: String },
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServerConfig {
    pub items: Vec<ConfigItem>,
}

impl ServerConfig {
    /// Load and parse a `serverconfig.xml` file.
    pub fn load(path: &Path) -> Result<Self> {
        let body = std::fs::read_to_string(path)
            .with_context(|| format!("reading config {}", path.display()))?;
        Self::parse(&body)
    }

    /// Save this config back out to disk as XML.
    pub fn save(&self, path: &Path) -> Result<()> {
        let xml = self.to_xml()?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating config directory {}", parent.display()))?;
        }
        std::fs::write(path, xml)
            .with_context(|| format!("writing config {}", path.display()))?;
        Ok(())
    }

    /// Parse from a string of XML.
    pub fn parse(xml: &str) -> Result<Self> {
        let mut reader = Reader::from_str(xml);
        reader.trim_text(true);

        let mut items: Vec<ConfigItem> = Vec::new();
        let mut buf = Vec::new();
        let mut inside_settings = false;

        loop {
            match reader.read_event_into(&mut buf) {
                Err(e) => return Err(anyhow!("xml error at pos {}: {}", reader.buffer_position(), e)),
                Ok(Event::Eof) => break,

                Ok(Event::Start(e)) if e.name().as_ref() == b"ServerSettings" => {
                    inside_settings = true;
                }
                Ok(Event::End(e)) if e.name().as_ref() == b"ServerSettings" => {
                    inside_settings = false;
                }

                Ok(Event::Empty(e)) | Ok(Event::Start(e))
                    if inside_settings && e.name().as_ref() == b"property" =>
                {
                    let mut name = None;
                    let mut value = None;
                    for attr in e.attributes().flatten() {
                        let key = attr.key.as_ref();
                        let val = attr
                            .decode_and_unescape_value(&reader)
                            .unwrap_or_default()
                            .into_owned();
                        match key {
                            b"name" => name = Some(val),
                            b"value" => value = Some(val),
                            _ => {}
                        }
                    }
                    if let (Some(n), Some(v)) = (name, value) {
                        items.push(ConfigItem::Property { name: n, value: v });
                    }
                }

                Ok(Event::Comment(c)) if inside_settings => {
                    let text = c
                        .unescape()
                        .map(|s| s.to_string())
                        .unwrap_or_else(|_| String::new());
                    items.push(ConfigItem::Comment { text });
                }

                _ => {}
            }
            buf.clear();
        }

        Ok(Self { items })
    }

    /// Render back out to XML.
    pub fn to_xml(&self) -> Result<String> {
        let mut writer = Writer::new_with_indent(Vec::new(), b' ', 4);

        writer.write_event(Event::Decl(BytesDecl::new("1.0", Some("UTF-8"), None)))?;

        // Top-level header so the file feels familiar.
        writer.write_event(Event::Comment(BytesText::new(
            " Generated by sdtd-server-manager. See https://7daystodie.com for game docs. ",
        )))?;

        let root = BytesStart::new("ServerSettings");
        writer.write_event(Event::Start(root))?;

        for item in &self.items {
            match item {
                ConfigItem::Property { name, value } => {
                    let mut elem = BytesStart::new("property");
                    elem.push_attribute(("name", name.as_str()));
                    elem.push_attribute(("value", value.as_str()));
                    writer.write_event(Event::Empty(elem))?;
                }
                ConfigItem::Comment { text } => {
                    writer.write_event(Event::Comment(BytesText::new(text)))?;
                }
            }
        }

        writer.write_event(Event::End(BytesEnd::new("ServerSettings")))?;

        let bytes = writer.into_inner();
        Ok(String::from_utf8(bytes).context("serialized xml was not utf-8")?)
    }

    /// Find the value of a property by name, if present.
    pub fn get(&self, name: &str) -> Option<&str> {
        self.items.iter().find_map(|i| match i {
            ConfigItem::Property { name: n, value } if n == name => Some(value.as_str()),
            _ => None,
        })
    }

    /// Update a property's value by name. Adds it if missing.
    pub fn set(&mut self, name: &str, value: impl Into<String>) {
        let value = value.into();
        for item in self.items.iter_mut() {
            if let ConfigItem::Property { name: n, value: v } = item {
                if n == name {
                    *v = value;
                    return;
                }
            }
        }
        self.items.push(ConfigItem::Property {
            name: name.to_string(),
            value,
        });
    }

    /// Replace the full property set with the supplied list. Comments are
    /// preserved at their original positions. Existing properties keep
    /// their slot in the file; new properties are appended at the end.
    pub fn merge_properties(&mut self, props: Vec<(String, String)>) {
        use std::collections::{HashMap, HashSet};

        let incoming: HashMap<String, String> = props.into_iter().collect();
        let mut updated: HashSet<String> = HashSet::new();

        // Update existing properties in place.
        for item in self.items.iter_mut() {
            if let ConfigItem::Property { name, value } = item {
                if let Some(new_value) = incoming.get(name) {
                    *value = new_value.clone();
                    updated.insert(name.clone());
                }
            }
        }

        // Append any properties that didn't exist before.
        for (name, value) in incoming {
            if !updated.contains(&name) {
                self.items
                    .push(ConfigItem::Property { name, value });
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_simple() {
        let xml = r#"<?xml version="1.0"?>
<ServerSettings>
    <!-- General -->
    <property name="ServerName" value="Test"/>
    <property name="ServerPort" value="26900"/>
</ServerSettings>"#;
        let cfg = ServerConfig::parse(xml).unwrap();
        assert_eq!(cfg.get("ServerName"), Some("Test"));
        assert_eq!(cfg.get("ServerPort"), Some("26900"));
        let out = cfg.to_xml().unwrap();
        assert!(out.contains("ServerName"));
        assert!(out.contains("26900"));
    }

    #[test]
    fn set_updates_existing() {
        let mut cfg = ServerConfig::default();
        cfg.set("ServerName", "Alpha");
        cfg.set("ServerName", "Bravo");
        assert_eq!(cfg.get("ServerName"), Some("Bravo"));
        // exactly one property entry
        let count = cfg.items.iter().filter(|i| matches!(i, ConfigItem::Property{..})).count();
        assert_eq!(count, 1);
    }
}
